{% set name = "ansiwrap" %}
{% set version = "0.8.4" %}
{% set bundle = "zip" %}
{% set hash_type = "sha256" %}
{% set hash_value = "ca0c740734cde59bf919f8ff2c386f74f9a369818cdc60efe94893d01ea8d9b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_value }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - textwrap3

test:
  imports:
    - ansiwrap

about:
  home: https://github.com/jonathaneunice/ansiwrap
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: textwrap, but savvy to ANSI colors and styles
  description: 'ansiwrap wraps text, like the standard textwrap module. But it also correctly wraps text that contains ANSI control sequences that colorize or style text.'
  dev_url: https://github.com/jonathaneunice/ansiwrap
